[package]
name = "cairo-lang-defs"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Handling of definitions of language items in Cairo."

[dependencies]
<<<<<<< HEAD
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.0.2" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "2.0.2" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.0.2" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "2.0.2" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "2.0.2" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.0.2" }
||||||| 1003d5d14
cairo-lang-debug = { path = "../cairo-lang-debug", version = "1.1.0" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "1.1.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "1.1.0" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "1.1.0" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "1.1.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.0" }
=======
cairo-lang-debug = { path = "../cairo-lang-debug", version = "1.1.1" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "1.1.1" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "1.1.1" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "1.1.1" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "1.1.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.1" }
>>>>>>> dev-v1.1.1
indexmap.workspace = true
itertools.workspace = true
salsa.workspace = true
smol_str.workspace = true

[dev-dependencies]
<<<<<<< HEAD
cairo-lang-test-utils = { path = "../cairo-lang-test-utils" }
||||||| 1003d5d14
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", version = "1.1.0" }
=======
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", version = "1.1.1" }
>>>>>>> dev-v1.1.1
env_logger.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
