[package]
name = "cairo-lang-syntax"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo syntax representation."

[dependencies]
<<<<<<< HEAD
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.0.2" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.0.2" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.0.2" }
||||||| 1003d5d14
cairo-lang-debug = { path = "../cairo-lang-debug", version = "1.1.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "1.1.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.0" }
=======
cairo-lang-debug = { path = "../cairo-lang-debug", version = "1.1.1" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "1.1.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.1" }
>>>>>>> dev-v1.1.1
num-bigint.workspace = true
num-traits.workspace = true
salsa.workspace = true
smol_str.workspace = true
thiserror.workspace = true
unescaper.workspace = true

[dev-dependencies]
env_logger.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
