[package]
name = "cairo-lang-syntax"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo syntax representation."

[dependencies]
<<<<<<< HEAD
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.3.0-rc0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.3.0-rc0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.3.0-rc0" }
itertools.workspace = true
||||||| 9b1d0a9fd
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.3.0-rc0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.3.0-rc0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.3.0-rc0" }
=======
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.3.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.3.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.3.0" }
>>>>>>> origin/dev-v2.3.0
num-bigint.workspace = true
num-traits.workspace = true
salsa.workspace = true
smol_str.workspace = true
unescaper.workspace = true

[dev-dependencies]
env_logger.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
