[package]
name = "cairo-lang-syntax"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo syntax representation."

[dependencies]
<<<<<<< HEAD
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.5.0-dev.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.5.0-dev.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.5.0-dev.0" }
num-bigint.workspace = true
num-traits.workspace = true
||||||| 1c02dc554
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.4.1" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.4.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.1" }
num-bigint.workspace = true
num-traits.workspace = true
=======
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.4.4" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.4.4" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.4" }
num-bigint = { workspace = true, default-features = true }
num-traits = { workspace = true, default-features = true }
>>>>>>> origin/main
salsa.workspace = true
smol_str.workspace = true
unescaper.workspace = true

[dev-dependencies]
env_logger.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
