[package]
name = "cairo-lang-project"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo project specification. For example, crates and flags used for compilation."

[dependencies]
<<<<<<< HEAD
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.5.0-dev.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.5.0-dev.0" }
serde.workspace = true
||||||| 1c02dc554
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.4.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.1" }
serde.workspace = true
=======
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.4.4" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.4" }
serde = { workspace = true, default-features = true }
>>>>>>> origin/main
smol_str.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
indoc.workspace = true
pretty_assertions.workspace = true
