[package]
name = "cairo-lang-project"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo project specification. For example, crates and flags used for compilation."

[dependencies]
<<<<<<< HEAD
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.4.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.1" }
serde = { workspace = true, default-features = true }
||||||| 34923c147
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.4.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.1" }
serde.workspace = true
=======
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.4.3" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.3" }
serde.workspace = true
>>>>>>> origin/dev-v2.4.3
smol_str.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
indoc.workspace = true
pretty_assertions.workspace = true
