[package]
name = "cairo-lang-diagnostics"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Diagnostic utilities."

[dependencies]
<<<<<<< HEAD
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.6.0-rc.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.6.0-rc.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.6.0-rc.0" }
||||||| 65da2b480
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.5.3" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.5.3" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.5.3" }
=======
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.5.4" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.5.4" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.5.4" }
>>>>>>> origin/main
itertools = { workspace = true, default-features = true }

[dev-dependencies]
env_logger.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
