[package]
name = "cairo-lang-diagnostics"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Diagnostic utilities."

[dependencies]
<<<<<<< HEAD
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.5.0-dev.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.5.0-dev.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.5.0-dev.0" }
itertools.workspace = true
||||||| 1c02dc554
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.4.1" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.4.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.1" }
itertools.workspace = true
=======
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.4.4" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.4.4" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.4" }
itertools = { workspace = true, default-features = true }
>>>>>>> origin/main

[dev-dependencies]
env_logger.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
