[package]
name = "cairo-lang-diagnostics"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Diagnostic utilities."

[dependencies]
<<<<<<< HEAD
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.4.1" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.4.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.1" }
itertools = { workspace = true, default-features = true }
||||||| 34923c147
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.4.1" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.4.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.1" }
itertools.workspace = true
=======
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.4.3" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.4.3" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.3" }
itertools.workspace = true
>>>>>>> origin/dev-v2.4.3

[dev-dependencies]
env_logger.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
