[package]
name = "cairo-lang-diagnostics"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Diagnostic utilities."

[dependencies]
<<<<<<< HEAD
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.0.2" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.0.2" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.0.2" }
||||||| 1003d5d14
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "1.1.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.0" }
=======
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "1.1.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.1" }
>>>>>>> dev-v1.1.1
itertools.workspace = true
salsa.workspace = true

[dev-dependencies]
<<<<<<< HEAD
cairo-lang-proc-macros = { path = "../cairo-lang-proc-macros" }
||||||| 1003d5d14
cairo-lang-proc-macros = { path = "../cairo-lang-proc-macros", version = "1.1.0" }
=======
cairo-lang-proc-macros = { path = "../cairo-lang-proc-macros", version = "1.1.1" }
>>>>>>> dev-v1.1.1
env_logger.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
