[package]
name = "cairo-lang-eq-solver"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Equation solving for Sierra generation."

[dependencies]
<<<<<<< HEAD
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.5.0-dev.0" }
||||||| 1c02dc554
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.1" }
=======
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.4" }
>>>>>>> origin/main
good_lp.workspace = true

[dev-dependencies]
env_logger.workspace = true
test-log.workspace = true
