[package]
name = "cairo-lang-eq-solver"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Equation solving for Sierra generation."

[dependencies]
<<<<<<< HEAD
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.0.2" }
||||||| 1003d5d14
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.0" }
=======
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.1" }
>>>>>>> dev-v1.1.1
good_lp.workspace = true
indexmap.workspace = true
itertools.workspace = true

[dev-dependencies]
env_logger.workspace = true
indoc.workspace = true
test-case.workspace = true
test-log.workspace = true
