[package]
name = "cairo-lang-plugins"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo core plugin implementations."

[dependencies]
<<<<<<< HEAD
cairo-lang-defs = { path = "../cairo-lang-defs", version = "2.0.2" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "2.0.2" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.0.2" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "2.0.2" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", version = "2.0.2" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "2.0.2" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.0.2" }
||||||| 1003d5d14
cairo-lang-defs = { path = "../cairo-lang-defs", version = "1.1.0" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "1.1.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "1.1.0" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "1.1.0" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", version = "1.1.0" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "1.1.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.0" }
=======
cairo-lang-defs = { path = "../cairo-lang-defs", version = "1.1.1" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "1.1.1" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "1.1.1" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "1.1.1" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", version = "1.1.1" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "1.1.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.1" }
>>>>>>> dev-v1.1.1
indoc.workspace = true
itertools.workspace = true
num-bigint.workspace = true
salsa.workspace = true
smol_str.workspace = true

[dev-dependencies]
<<<<<<< HEAD
cairo-lang-debug = { path = "../cairo-lang-debug" }
cairo-lang-parser = { path = "../cairo-lang-parser" }
cairo-lang-test-utils = { path = "../cairo-lang-test-utils" }
||||||| 1003d5d14
cairo-lang-debug = { path = "../cairo-lang-debug", version = "1.1.0" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "1.1.0" }
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", version = "1.1.0" }
=======
cairo-lang-debug = { path = "../cairo-lang-debug", version = "1.1.1" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "1.1.1" }
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", version = "1.1.1" }
>>>>>>> dev-v1.1.1
env_logger.workspace = true
indoc.workspace = true
serde_json.workspace = true
test-case.workspace = true
test-log.workspace = true
