[package]
name = "starknet-sierra-extract-code"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Compiler executable for printing Starknet Sierra json included code"

[dependencies]
anyhow.workspace = true
cairo-lang-starknet-classes = { path = "../../cairo-lang-starknet-classes", version = "2.5.3" }
clap.workspace = true
serde_json.workspace = true
<<<<<<< HEAD
||||||| 2789b60a1
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "2.5.3" }
=======
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "2.5.4" }
>>>>>>> origin/dev-v2.5.4
