[package]
name = "cairo-test"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Test runner for the Cairo programming language"

[dependencies]
anyhow.workspace = true
clap.workspace = true

<<<<<<< HEAD
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "2.0.0-rc5" }
cairo-lang-test-runner = { path = "../../cairo-lang-test-runner", version = "2.0.0-rc5" }
||||||| 801265d38
cairo-lang-test-runner = { path = "../../cairo-lang-test-runner", version = "2.0.0-rc5" }
=======
cairo-lang-test-runner = { path = "../../cairo-lang-test-runner", version = "2.0.0" }
>>>>>>> origin/dev-v2.0.0
