[package]
name = "cairo-lang-sierra-type-size"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Sierra type sizes computation."

[dependencies]
<<<<<<< HEAD
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.5.0-dev.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.5.0-dev.0" }
||||||| 1c02dc554
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.4.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.1" }
=======
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.4.4" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.4" }
>>>>>>> origin/main
