[package]
name = "cairo-lang-sierra-type-size"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Sierra type sizes computation."

[dependencies]
<<<<<<< HEAD
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.6.0-rc.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.6.0-rc.0" }
||||||| 65da2b480
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.5.3" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.5.3" }
=======
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.5.4" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.5.4" }
>>>>>>> origin/main
