[package]
name = "sierra-compile"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Compiler executable for the Sierra intemediate representation"

[dependencies]
anyhow.workspace = true
log.workspace = true
clap.workspace = true
indoc.workspace = true

<<<<<<< HEAD
cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "2.5.0-dev.0" }
cairo-lang-sierra-to-casm = { path = "../../cairo-lang-sierra-to-casm", version = "2.5.0-dev.0" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.5.0-dev.0", features = [
||||||| 1c02dc554
cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "2.4.1" }
cairo-lang-sierra-to-casm = { path = "../../cairo-lang-sierra-to-casm", version = "2.4.1" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.4.1", features = [
=======
cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "2.4.4" }
cairo-lang-sierra-to-casm = { path = "../../cairo-lang-sierra-to-casm", version = "2.4.4" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.4.4", features = [
>>>>>>> origin/main
    "env_logger",
] }
