[package]
name = "cairo-lang-sierra-gas"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Sierra gas computation."

[dependencies]
<<<<<<< HEAD
cairo-lang-eq-solver = { path = "../cairo-lang-eq-solver", version = "2.6.0-rc.0" }
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.6.0-rc.0" }
cairo-lang-sierra-type-size = { path = "../cairo-lang-sierra-type-size", version = "2.6.0-rc.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.6.0-rc.0" }
||||||| 65da2b480
cairo-lang-eq-solver = { path = "../cairo-lang-eq-solver", version = "2.5.3" }
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.5.3" }
cairo-lang-sierra-type-size = { path = "../cairo-lang-sierra-type-size", version = "2.5.3" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.5.3" }
=======
cairo-lang-eq-solver = { path = "../cairo-lang-eq-solver", version = "2.5.4" }
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.5.4" }
cairo-lang-sierra-type-size = { path = "../cairo-lang-sierra-type-size", version = "2.5.4" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.5.4" }
>>>>>>> origin/main
itertools = { workspace = true, default-features = true }
thiserror.workspace = true
num-traits = { workspace = true, default-features = true }

[dev-dependencies]
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
env_logger.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
test-case.workspace = true
test-log.workspace = true
