[package]
name = "cairo-lang-sierra-gas"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Sierra gas computation."

[dependencies]
<<<<<<< HEAD
cairo-lang-eq-solver = { path = "../cairo-lang-eq-solver", version = "2.5.0-dev.0" }
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.5.0-dev.0" }
cairo-lang-sierra-type-size = { path = "../cairo-lang-sierra-type-size", version = "2.5.0-dev.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.5.0-dev.0" }
itertools.workspace = true
||||||| 1c02dc554
cairo-lang-eq-solver = { path = "../cairo-lang-eq-solver", version = "2.4.1" }
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.4.1" }
cairo-lang-sierra-type-size = { path = "../cairo-lang-sierra-type-size", version = "2.4.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.1" }
itertools.workspace = true
=======
cairo-lang-eq-solver = { path = "../cairo-lang-eq-solver", version = "2.4.4" }
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.4.4" }
cairo-lang-sierra-type-size = { path = "../cairo-lang-sierra-type-size", version = "2.4.4" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.4" }
itertools = { workspace = true, default-features = true }
>>>>>>> origin/main
thiserror.workspace = true
num-traits = { workspace = true, default-features = true }

[dev-dependencies]
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
env_logger.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
test-case.workspace = true
test-log.workspace = true
