[package]
name = "cairo-lang-sierra-gas"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Sierra gas computation."

[dependencies]
<<<<<<< HEAD
cairo-lang-eq-solver = { path = "../cairo-lang-eq-solver", version = "2.0.1" }
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.0.1" }
cairo-lang-sierra-type-size = { path = "../cairo-lang-sierra-type-size", version = "2.0.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.0.1" }
||||||| cf142a28e
cairo-lang-eq-solver = { path = "../cairo-lang-eq-solver", version = "2.0.1" }
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.0.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.0.1" }
=======
cairo-lang-eq-solver = { path = "../cairo-lang-eq-solver", version = "2.0.2" }
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.0.2" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.0.2" }
>>>>>>> v2.0.2
itertools.workspace = true
thiserror.workspace = true

[dev-dependencies]
<<<<<<< HEAD
cairo-lang-test-utils = { path = "../cairo-lang-test-utils" }
||||||| cf142a28e
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", version = "2.0.1" }
=======
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", version = "2.0.2" }
>>>>>>> v2.0.2
env_logger.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
test-case.workspace = true
test-log.workspace = true
