[package]
name = "generate-syntax"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
log.workspace = true

<<<<<<< HEAD
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.6.0-rc.0", features = [
||||||| 65da2b480
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.5.3", features = [
=======
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.5.4", features = [
>>>>>>> origin/main
    "env_logger",
] }
<<<<<<< HEAD
cairo-lang-syntax-codegen = { path = "../../cairo-lang-syntax-codegen", version = "2.6.0-rc.0" }
||||||| 65da2b480
cairo-lang-syntax-codegen = { path = "../../cairo-lang-syntax-codegen", version = "2.5.3" }
=======
cairo-lang-syntax-codegen = { path = "../../cairo-lang-syntax-codegen", version = "2.5.4" }
>>>>>>> origin/main
