[package]
name = "cairo-lang-formatter"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo formatter."

[dependencies]
anyhow.workspace = true
<<<<<<< HEAD
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "2.0.2" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.0.2" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "2.0.2" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "2.0.2" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.0.2" }
||||||| 1003d5d14
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "1.1.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "1.1.0" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "1.1.0" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "1.1.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.0" }
clap.workspace = true
=======
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "1.1.1" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "1.1.1" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "1.1.1" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "1.1.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.1" }
clap.workspace = true
>>>>>>> dev-v1.1.1
colored.workspace = true
diffy.workspace = true
ignore.workspace = true
itertools.workspace = true
log.workspace = true
salsa.workspace = true
smol_str.workspace = true

[dev-dependencies]
<<<<<<< HEAD
||||||| 1003d5d14
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.0" }
=======
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.1" }
>>>>>>> dev-v1.1.1
pretty_assertions.workspace = true
test-case.workspace = true
test-log.workspace = true
