[package]
name = "cairo-lang-debug"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Debug utilities for query objects."

[dependencies]
<<<<<<< HEAD
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.6.0-rc.0" }
||||||| 65da2b480
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.5.3" }
=======
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.5.4" }
>>>>>>> origin/main

[dev-dependencies]
cairo-lang-proc-macros = { path = "../cairo-lang-proc-macros"}
env_logger.workspace = true
salsa.workspace = true
test-log.workspace = true
