[package]
name = "cairo-compile"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo compiler executable for the Cairo programming language"

[dependencies]
anyhow.workspace = true
clap.workspace = true
log.workspace = true

<<<<<<< HEAD
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "2.6.0-rc.0" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.6.0-rc.0", features = [
||||||| 65da2b480
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "2.5.3" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.5.3", features = [
=======
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "2.5.4" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.5.4", features = [
>>>>>>> origin/main
    "env_logger",
] }
