[package]
name = "cairo-lang-test-utils"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Utilities for writing tests in the Cairo compiler project."

[dependencies]
<<<<<<< HEAD
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.0.2" }
||||||| 1003d5d14
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.0" }
=======
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.1" }
>>>>>>> dev-v1.1.1
log.workspace = true
pretty_assertions.workspace = true

[dev-dependencies]
test-log.workspace = true
env_logger.workspace = true
