[package]
name = "cairo-lang-proc-macros"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Procedural macros."

[lib]
proc-macro = true

[package.metadata.cargo-machete]
ignored = ["cairo-lang-debug"]

[package.metadata.cargo-udeps.ignore]
normal = ["cairo-lang-debug"]

[dependencies]
# This is used only for docs.
<<<<<<< HEAD
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.6.0-rc.0" }
||||||| 65da2b480
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.5.3" }
=======
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.5.4" }
>>>>>>> origin/main
quote.workspace = true
syn.workspace = true
