[package]
name = "cairo-lang-syntax-codegen"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo syntax code generation."

[package.metadata.cargo-udeps.ignore]
normal = ["cairo-lang-syntax"]

[dependencies]
<<<<<<< HEAD
||||||| 1003d5d14
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.0" }
=======
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.1" }
>>>>>>> dev-v1.1.1
genco.workspace = true
xshell.workspace = true

[dev-dependencies]
env_logger.workspace = true
test-log.workspace = true
